language: ruby

services:
  - docker

before_install:
  - docker build -t joelin/nextpos-app:latest .

script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/source -e USERNAME=$EXPO_USERNAME -e PASSWORD=$EXPO_PASSWORD joelin/nextpos-app:latest
